development:
  adapter: postgresql
  database: rocm_dev
  username: rocm_dev
  password: r0cm_d3v

test:
  adapter: postgresql
  database: rocm_dev
  username: rocm_test
  password: r0cm_t3st

production:
  adapter: postgresql
  database: rocm_dev
  username: rocm_pro
  password: r0cm_pr0